MAINTENANCE_QA_GUIDANCE = [
    {
        "id": 268,
        "problem": "Basic Maintenance Schedule Guidance",
        "system": "maintenance",
        "component": "service schedule",
        "severity": "low",
        "urgency": "normal",
        "probability": 4,
        "symptoms": [
            "basic maintenance question",
            "service schedule question",
            "routine maintenance checklist",
            "what maintenance should i do",
            "periodic service due",
        ],
        "questions": [
            {"id": "q1", "text": "Car ka last service kab hua tha?", "impact": {"yes": 1.2, "no": 1.0}},
            {"id": "q2", "text": "Koi warning light ya abnormal sound hai?", "impact": {"yes": 1.5, "no": 0.8}},
        ],
        "user_checks": [
            "check engine oil level and service sticker",
            "check tyre pressure and visible tyre wear",
            "check coolant, brake fluid, all lights, wipers and battery terminals",
        ],
        "repair_cost": {"min": 0, "max": 5000},
        "advice": "Follow the owner manual first. As a baseline, inspect fluids, filters, tyres, brakes, lights and battery before long trips or every service interval.",
    },
    {
        "id": 269,
        "problem": "Engine Oil Change Guidance",
        "system": "maintenance",
        "component": "engine oil",
        "severity": "low",
        "urgency": "normal",
        "probability": 5,
        "symptoms": [
            "engine oil change question",
            "when to change engine oil",
            "oil service due",
            "engine oil maintenance",
            "which engine oil interval",
        ],
        "questions": [
            {"id": "q1", "text": "Oil change due date ya km cross ho gaya hai?", "impact": {"yes": 1.5, "no": 0.8}},
            {"id": "q2", "text": "Oil level low ya oil warning light ON hai?", "impact": {"yes": 1.7, "no": 0.6}},
        ],
        "user_checks": [
            "check oil level on dipstick when parked safely",
            "follow the grade and interval in the owner manual",
            "if oil pressure warning is ON, stop driving and inspect immediately",
        ],
        "repair_cost": {"min": 1500, "max": 8000},
        "advice": "Do not guess oil grade. Use manufacturer-specified grade and interval. Severe city use, heat, dust and short trips may need earlier replacement.",
    },
    {
        "id": 270,
        "problem": "Tyre Pressure And Rotation Guidance",
        "system": "maintenance",
        "component": "tyres",
        "severity": "low",
        "urgency": "normal",
        "probability": 5,
        "symptoms": [
            "tyre pressure question",
            "tire pressure question",
            "when to rotate tyres",
            "tyre rotation maintenance",
            "tyre maintenance checklist",
        ],
        "questions": [
            {"id": "q1", "text": "Tyre pressure monthly check karte ho?", "impact": {"yes": 1.1, "no": 1.4}},
            {"id": "q2", "text": "Uneven tyre wear ya pulling feel hota hai?", "impact": {"yes": 1.5, "no": 0.8}},
        ],
        "user_checks": [
            "check tyre pressure when tyres are cold",
            "inspect sidewall cuts, bulges and uneven wear",
            "do wheel alignment/balancing if pulling, vibration or uneven wear appears",
        ],
        "repair_cost": {"min": 0, "max": 4000},
        "advice": "Use the tyre pressure label/manual value, not the maximum pressure printed on the tyre. Rotate tyres based on owner manual or tyre wear pattern.",
    },
    {
        "id": 271,
        "problem": "Battery Maintenance Guidance",
        "system": "maintenance",
        "component": "battery",
        "severity": "low",
        "urgency": "normal",
        "probability": 5,
        "symptoms": [
            "battery maintenance question",
            "battery health check question",
            "when to replace battery",
            "battery service guidance",
            "battery weak prevention",
        ],
        "questions": [
            {"id": "q1", "text": "Morning start slow ho raha hai?", "impact": {"yes": 1.5, "no": 0.8}},
            {"id": "q2", "text": "Battery 3-5 saal purani hai?", "impact": {"yes": 1.4, "no": 0.8}},
        ],
        "user_checks": [
            "inspect terminal corrosion and tightness",
            "get a battery load test before replacement",
            "check alternator charging voltage if battery warning light appears",
        ],
        "repair_cost": {"min": 0, "max": 12000},
        "advice": "Battery life depends on heat, usage and alternator health. Test before replacing; repeated discharge can also be caused by parasitic drain.",
    },
    {
        "id": 272,
        "problem": "Brake Maintenance Guidance",
        "system": "maintenance",
        "component": "brake system",
        "severity": "medium",
        "urgency": "service_soon",
        "probability": 4,
        "symptoms": [
            "brake maintenance question",
            "when to change brake pads",
            "brake service guidance",
            "brake fluid maintenance",
            "brake inspection checklist",
        ],
        "questions": [
            {"id": "q1", "text": "Brake noise, vibration ya weak braking feel hota hai?", "impact": {"yes": 1.7, "no": 0.7}},
            {"id": "q2", "text": "Brake fluid level low hai?", "impact": {"yes": 1.6, "no": 0.7}},
        ],
        "user_checks": [
            "inspect brake pad thickness and disc condition",
            "check brake fluid level and leaks",
            "avoid driving if brake pedal is soft, sinking or warning light is ON",
        ],
        "repair_cost": {"min": 0, "max": 12000},
        "advice": "Brake maintenance is safety-critical. Do not ignore noise, vibration, soft pedal, fluid loss or warning lights.",
    },
    {
        "id": 273,
        "problem": "Coolant Maintenance Guidance",
        "system": "maintenance",
        "component": "coolant system",
        "severity": "medium",
        "urgency": "service_soon",
        "probability": 4,
        "symptoms": [
            "coolant maintenance question",
            "coolant level check question",
            "when to change coolant",
            "radiator coolant guidance",
            "cooling system maintenance",
        ],
        "questions": [
            {"id": "q1", "text": "Coolant level low ya leak visible hai?", "impact": {"yes": 1.6, "no": 0.8}},
            {"id": "q2", "text": "Temperature warning ya overheating hoti hai?", "impact": {"yes": 1.8, "no": 0.6}},
        ],
        "user_checks": [
            "check coolant only when engine is cool",
            "do not open radiator cap when hot",
            "inspect hoses, radiator fan, reservoir and leak marks",
        ],
        "repair_cost": {"min": 500, "max": 8000},
        "advice": "Use the correct coolant type and mix. Overheating or coolant loss is not routine maintenance; it needs inspection.",
    },
    {
        "id": 274,
        "problem": "Filter Maintenance Guidance",
        "system": "maintenance",
        "component": "air/cabin/fuel filters",
        "severity": "low",
        "urgency": "normal",
        "probability": 4,
        "symptoms": [
            "filter maintenance question",
            "air filter change question",
            "cabin filter change question",
            "fuel filter maintenance",
            "service filter checklist",
        ],
        "questions": [
            {"id": "q1", "text": "Dusty area me car zyada chalti hai?", "impact": {"yes": 1.4, "no": 0.8}},
            {"id": "q2", "text": "AC airflow weak ya smell aa rahi hai?", "impact": {"yes": 1.5, "no": 0.8}},
        ],
        "user_checks": [
            "inspect air filter for dust/clogging",
            "replace cabin filter if AC airflow is weak or smell appears",
            "follow manual for fuel filter interval, especially diesel cars",
        ],
        "repair_cost": {"min": 300, "max": 6000},
        "advice": "Filters are low-cost but affect mileage, AC airflow and engine health. Replace earlier in dusty conditions.",
    },
    {
        "id": 275,
        "problem": "Long Trip Maintenance Checklist",
        "system": "maintenance",
        "component": "trip checklist",
        "severity": "low",
        "urgency": "normal",
        "probability": 5,
        "symptoms": [
            "long trip maintenance checklist",
            "highway trip car check",
            "before road trip maintenance",
            "long drive checklist",
            "trip se pehle maintenance",
        ],
        "questions": [
            {"id": "q1", "text": "Long trip 200 km se zyada hai?", "impact": {"yes": 1.3, "no": 0.8}},
            {"id": "q2", "text": "Recent service overdue hai?", "impact": {"yes": 1.5, "no": 0.8}},
        ],
        "user_checks": [
            "check tyre pressure, spare tyre, jack and puncture kit",
            "check engine oil, coolant, brake fluid and washer fluid",
            "check lights, wipers, battery health and emergency contacts",
        ],
        "repair_cost": {"min": 0, "max": 5000},
        "advice": "Before a long trip, fix warning lights, weak brakes, overheating, tyre damage or battery weakness first. Do not rely on last-minute visual checks only.",
    },
]

